### PR TITLE
 A number of fixes to CSS and processing of variants 

### PR DESCRIPTION
**Pull request by raffazizzi**
Updated viewer to display the score in full and to display variants in popups more clearly. Other issues are still open, particularly related to the positioning of popus.

Improvements to CSS for TEI text display, updated JS libraries (CETEIcean and Verovio).

### CODE REVIEW

**Comment by MarcusBarnes** [comment]
I've started testing this.  One thing I noticed was some conflicting interactions with the Overlay module in Drupal.  To reproduce the behaviour, use a collation such as "Aged man that moves these fields" from the songscapes in your development environment.   You'll need to adjust the paths to the MEI and TEI files to match the object PID that is created when you upload the collation file as your OBJ file.  Add the associated MEI and TEI files (again, updating the object PID in the paths within the XML as required).  Once the TEI and MEI render, make sure you have permissions to click the object manage tab.  Clicking the tab will pull-up the admin overlay when the Overlay module is enabled.  You'll see something like this:
untitled
Notice how the admin menu is being rendered again.  I didn't see this with previous PRs, so something is different.  It could be the naming conventions for the datastreams not being parsed correctly by the Overlay module.  The short-term solution is to disable the Overlay module, but I'd like to sort out what the issue may be in case there are other unintentional conflicting interactions with core-Drupal modules or default Islandora modules. 


@raffazizzi Is the included version of Verovio correct?  Do we also need to include the CETEIcean library in https://github.com/digitalutsc/ems/tree/master/lib or is it in the compiled bundle.js file?

**Comment by raffazizzi** [comment]
@MarcusBarnes I've been digging around for a couple of hours, but I'm not sure what's going on. I made sure to "isolate" the CSS by prefixing everything with `#ems_viewer` (which is trivial to do with scss), but the problem remained.

Then I noticed that the overlay gets appended inside `#ems_viewer`! (see screenshot) can you think of any reason why that may be happening?

screenshot from 2018-12-06 15-12-14

Another things to consider is how the overlay gets called using fragments and how the web application also relies on fragments to choose which source to show. The newer version of CETEIcean (which handles the TEI rendering) also reads the hash, but I thought it was fairly innocuous since it just throws an error and continues: `'#/&overlay=islandora/object/islandora%253A1/manage' is not a valid selector`

Interestingly, all CETEIcean errors and warnings are getting thrown via  jquery.min.js according to Firefox. What gives?

**Comment by raffazizzi** [comment]
Ok - I *think* I know what's going on. The duplicate page we see is a 404 error page that my code pulls in when trying to load a source by reading the URL fragment. [See this line of code](https://github.com/EarlyModernSongscapes/songscapes-viewer/blob/master/src/components/AppBody.js#L12).

I can try and stop fragments that are clearly from islandora, but I wonder if it would make more sense to disable the overlay?

**Comment by raffazizzi** [comment]
Actually, I've added a simple check for avoiding attempting to use the overaly parameters as a source. I figure the webapp should be able to handle this more gracefully, eventually. 

Anyway, it seems to work now. The only drawback is that when the overlay is called, the webapp returns to show the first source (as if there were no parameters). But I think this is tolerable.

**Comment by MarcusBarnes** [comment]
@raffazizzi Awesome.  Thanks for investigating.  I'll test soon.

**Comment by raffazizzi** [comment]
@MarcusBarnes I've also added a fix for the popup css - I think this should take care of it, but let me know if you notice something unusual

**Comment by MarcusBarnes** [comment]
@raffazizzi I've tested the additional changes you pushed in my local dev. environment.  The changes appear to address the issue I noted in comment https://github.com/digitalutsc/ems/pull/7#issuecomment-443856408.   I'm going to merge and we can do further work refining how the popups display as needed in separate issues and pull-requests.  Thanks!

**Pull request merged**
